# Seeds are fully generated by AI (ChatGPT)

from app import create_app, db
from app.models import Story, Page, Choice

app = create_app()

with app.app_context():
    # Optional: Clear everything for a clean test
    db.drop_all()
    db.create_all()

    # 1. Create the Story
    s = Story(title="The Python Internship", description="A quest for clean code.")
    db.session.add(s)
    db.session.flush()

    # 2. Create the Pages
    p1 = Page(text="You sit at your desk. Your Senior Dev asks for a test. What do you do?", story_id=s.id)
    p2 = Page(text="You run a seed script. Everything works! You get a coffee.", story_id=s.id, is_ending=True,
              ending_label="Success")
    p3 = Page(text="You ignore the test. The server explodes in production.", story_id=s.id, is_ending=True,
              ending_label="Game Over")

    db.session.add_all([p1, p2, p3])
    db.session.flush()

    # 3. Create Choices
    c1 = Choice(text="Run the test", page_id=p1.id, next_page_id=p2.id)
    c2 = Choice(text="Ignore it", page_id=p1.id, next_page_id=p3.id)

    # 4. Set the Start Page
    s.start_page_id = p1.id

    db.session.add_all([c1, c2])
    db.session.commit()
    print("Test story created successfully!")