"""add start_page_id to story

Revision ID: 506e7d924080
Revises: 99bf04ce6d7f
Create Date: 2026-01-27 22:46:22.370380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506e7d924080'
down_revision = '99bf04ce6d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_page_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('start_page_id')

    # ### end Alembic commands ###
