"""initial migration with storynode

Revision ID: ed712c1ab000
Revises: 
Create Date: 2026-02-06 22:41:44.609309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed712c1ab000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('initial_state', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.String(length=50), nullable=True),
    sa.Column('node_type', sa.String(length=20), nullable=True),
    sa.Column('background', sa.String(length=100), nullable=True),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('affinity_change', sa.JSON(), nullable=True),
    sa.Column('is_ending', sa.Boolean(), nullable=True),
    sa.Column('ending_outcome', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_node_custom_id'), ['custom_id'], unique=False)

    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_custom_id', sa.String(length=50), nullable=True),
    sa.Column('effect_description', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['story_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choice')
    with op.batch_alter_table('story_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_node_custom_id'))

    op.drop_table('story_node')
    op.drop_table('story')
    # ### end Alembic commands ###
